language: python
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
python:
  - "2.6"
  - "2.7"
install:
  - pip install django==$DJANGO_VERSION
  - pip install .
script: ./test_project/manage.py test
